[behave]
paths        = features
format       = pretty
show_timings = true

[behave.userdata]
base_url           = https://www.saucedemo.com
# true = headless (CI) | false = navegador visible (local)
headless           = false
# Tiempo máximo de espera explícita en segundos
wait_timeout       = 10
# Capturar screenshot al fallar
screenshot_on_fail = true
# Navegador: chrome | firefox | edge
browser            = chrome
